### ISSUE TITLE
Value delete is not a member of

### ISSUE THREAD

**Issue by ArchDev** [playframework/play-slick#249]
Hello.

I found issues with usage of play-slick default driver instead of slick driver.
When use default play-slick driver, query method ".delete()" cannot be found.

Error definition:
```
value delete is not a member of slick.lifted.Query[UsersDao.this.UsersTable,UsersDao.this.UsersTable#TableElementType,Seq]
```

Example of code:
```
package dao

import models.User

import play.api.db.slick.DatabaseConfigProvider
import play.api.db.slick.HasDatabaseConfig
import play.api.libs.concurrent.Execution.Implicits.defaultContext
import play.api.Play

import slick.profile.RelationalProfile
import slick.backend.DatabaseConfig
import slick.jdbc.meta.MTable

import scala.concurrent.Future

class UsersDao extends HasDatabaseConfig[RelationalProfile] {
	val dbConfig: DatabaseConfig[RelationalProfile] = DatabaseConfigProvider.get[RelationalProfile](Play.current)
	import driver.api._
        // Change driver to this for fix.
	//import scala.slick.driver.PostgresDriver.api._

	protected val tableName = "users"
	protected val tableQuery = TableQuery[UsersTable]

	protected class UsersTable(tag: Tag) extends Table[User](tag, tableName) {
		def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
		def username = column[String]("username")
		def email = column[String]("email")
		def password = column[String]("password")

		def * = (id.?, username, email, password) <> ((User.apply _).tupled, User.unapply)
	}

	def createSchema() = db.run(tableQuery.schema.create)
	def find(page: Int, pageSize: Int): Future[Seq[User]] = db.run(tableQuery.drop((page - 1) * pageSize).take(pageSize).result)
	def delete(model: User): Future[Int] = db.run(tableQuery.filter(_.id === model.id).delete)
}
```

**Comment by kaifer** [comment]
".returning" also cannot be found!

**Comment by rcavalcanti** [comment]
You have to use a JdbcProfile instead. 
```
class UsersDao extends HasDatabaseConfig[JdbcProfile] {
 val dbConfig: DatabaseConfig[JdbcProfile] = DatabaseConfigProvider.get[JdbcProfile(Play.current)    
}
```
Btw, if you are interested in a DAO project for Slick you can check this:
https://github.com/strongtyped/active-slick/tree/feature/slick-3.0

I'm still working on the support for slick 3.0, but the branch is all useful.

**Comment by dotta** [comment]
I'm closing this issue as @rcavalcanti already provided the solution. Also, in the future, please ask this kind of questions in the playframework-user ML. Thanks!

**Comment by centaure** [comment]
Actually the solution proposed by  @rcavalcanti does not seem to work for me. I have to import slick.driver.MySQLDriver.api._ in order to get the following to compile:
  
    import play.api.libs.concurrent.Execution.Implicits._

    import play.api.db.slick.HasDatabaseConfig
    import slick.driver.JdbcProfile

    import scala.concurrent.Future
    import models.details.IDable
    import models.daos.slick.db.details.RichTable

    trait CRUDModel[T <: RichTable[A], A <: IDable[A]] extends HasDatabaseConfig[JdbcProfile] {
      import play.api.db.slick.DatabaseConfigProvider
      import slick.driver.MySQLDriver.api._
      // importing driver.api._ (instead of MySQLDriver.api._) results in error highlighted by @ArchDev
      // import driver.api._
  
      protected val dbConfig = DatabaseConfigProvider.get[JdbcProfile](play.api.Play.current)

      val tableQuery: TableQuery[T]
 
      def delete(id: Long): Future[Boolean] =
        db.run(tableQuery.filter(t => t.id === id).delete) map {
          case 0 => false
          case _ => true
        }

    }

**Comment by djx314** [comment]
If I can only import JdbcProfile, then I  can't use somehting like slick-pg to provide custom data type  to slick.

**Comment by djx314** [comment]
slick 3.1.0-M2 remove JdbcDriver, so I think this issue should be reopen.

**Comment by dotta** [comment]
@centaure As asked in my [last comment](https://github.com/playframework/play-slick/issues/249#issuecomment-113776712), please ask this kind of questions in either the playframework-user or Slick ML. Thanks!

**Comment by jdelafon** [comment]
I see that the error seems fixed in Slick 3.1.0, and their fix is referenced just above, but I still get the error with Play-slick 2.0.2 and I have no idea what to do about it:
    
    class DAO(driver: slick.driver.JdbcProfile, db: slick.driver.JdbcProfile#Backend#Database)
      import this.driver.api._
      ...
      db run action.delete()

gives:

    `value delete is not a member of slick.lifted.Query`

The `driver` and `db` are the things available from an injected controller, as suggested by the docs, i.e.:

    class MyController @Inject()(dbConfigProvider: DatabaseConfigProvider) extends Controller
      val dbConfig = dbConfigProvider.get[JdbcProfile]
      val driver: JdbcProfile = dbConfig.driver
      val db = dbConfig.db

Reopen ?

**Comment by magnusja** [comment]
@jdelafon Same for me.

**Comment by djx314** [comment]
@magnusja Already fixed in https://github.com/slick/slick/issues/1253

**Comment by jdelafon** [comment]
@djx314 Indeed, I referenced it above, yet I have this error with Play-slick 2.0.2 (that is, Slick 3.1, right?), please look at my post just over his, from 8 days ago.

Is there any way to get a version where this is really fixed? Can it be that there is an issue on the play-sick side? Or that it is not really fixed on the Slick side? In any case, just following the current play-slick docs gets me stuck without a delete operation.

**Comment by djx314** [comment]
@jdelafon use the lastest play-slick version and slick 3.1.1

**Comment by jdelafon** [comment]
I may be slow, but what else can I do?

libraryDependencies ++= Seq(
  "com.typesafe.slick" %% "slick" % "3.1.1",
  "org.slf4j" % "slf4j-nop" % "1.6.4",
  "com.typesafe.play" %% "play-slick" % "2.0.2",
  "com.typesafe.play" %% "play-slick-evolutions" % "2.0.2",
  "com.typesafe.slick" %% "slick-codegen" % "3.1.1"
)

**Comment by magnusja** [comment]
This helped me: https://stackoverflow.com/questions/40988143/value-delete-is-not-a-member-of-slick-lifted-queryt-ttableelementtype-seq/40989924?noredirect=1#comment69394043_40989924

**Comment by jdelafon** [comment]
Thanks @magnusja . It worked indeed, except the import is now

    slick.driver.<MySQLDriver>.profile.api.Table

to use instead of `AbstractTable`. It is a Slick issue, not a play-slick one. Thank god, because the playframework mailing list is not super helpful, and here they just don't read you.
